language: c
sudo: false
env:
  global:
    # Intel Parallel Studio
    - secure: "IK66gBj3RMbOqPAslQ2V09Sx8bV8aSHAdaO4beFuDXlRsaiBDqlKnII86Nw0ghELmwGAtH3Ow7I8pkjCyyB0v/R0ruOVW2SwPrtIcYGVEvT3BI9uQkCq9PInh4gdgdqsa5zxJU1XKtj9jX/gHbjlFgNJkXIlbvdttVQ8wad7EmSSv5i8Tb/gRDqa176lkGgSj5crMe072TEHuAe0Kllphol1mD0EjKkcfoFd9SBURG66aPuUOM4InSM+3o1Qw7t7+3oarOJPMu4eONAxp61iVWpIy1dRKGf1pYW5MwQ1JMkqc50MKF8EKjAwUVwggVTG7H5hntwwuDlzLyo33mEE8n//VbbjEBgozhyMcsYaIpPvGDA1bItgUohO8xf002JMG9bdbaC9jpU5TLLvg4rGDg6rbPTqtaIhTebA+xaWj2tHpf5Rv9D45EgtrxSfmMywGkoMf9iWEo1iGGgdmCMQKxwmmSG8FYIYJMGaq7Hmp8ZsCmQadOfaZM7ZdaMajSP6M05g7pggdeHofRwizUPlG6BUlAS+7FtJscM+i/6BMrViNlfw0ZUNEAcmbewDXKaab70a01rcAMXHu2p9q1fKX1L1V1788rzxkG5NY58SiWATFZnLzVtYnGpvdbX+Wq8a4Ms8O7628aigcGnLKvJys8dMniyTG169EtVdiz3xdxE="
matrix:
  include:
    ##
    # Test basic installation with different Travis environments
    ##
    # Ubuntu 12.04 container build
    - os: linux
      sudo: true
      env: COMPONENTS=ifort
before_install:
  - ./install-icc.sh --components "${COMPONENTS}"
  - source ~/.bashrc
  - chmod +x Asplundnew
script:
  # Fortran 90 compiler
  - ifort -save -o xnfdf.exe save/xnfdf.for 
  - ./Asplundnew
  - diff xnfpdf.dat.test xnfpdf.dat
  - diff xnfpdfmax.dat.test xnfpdfmax.dat.test

after_script:
  - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'

#notifications:
#  email:
#    on_success: change
#    on_failure: change
