language: c
sudo: false
env:
  global:
    # Intel Parallel Studio
    - secure: "pRthq4b59pqfe333JklO6VAuRR2OTfecg0X2cAznmzsmNj8AF/hL1HQCoUScPwSwLBfVCfaEK/sT1jXCG3nz1/TQtwtVuarQuylSzxnqJZJEubDOhpT8nNnvAqVvgGzsq7z4FgBUmk+Nv6nrFkf8FGqfgRY3/djeogmNWs8FYRPXeqnBUTix5mlTY1rim940RdTzipo8IlXhpux9Dwjr6U+jKaKDEqq3t5AMqmBAcF5KulNJhCbSQhIu3hNs7hhMGPyxbbX9FfYtBQ45IU87FqSOfUfp2jOmw+h1N6XMIlqXTtshR3IditvXkhtOY9Aw6QE39oX1ivCFzqnk2iFmNArWnOHIltTT72zKuwURX2WQU6y7FfsF1NrtGijHJsfqieRDgBWnfoNFm9nCJQSv6g/tFXsT95dmvipzvzqSGpkArTc6kWBkFnfKy9FfbLnHm9V2L+PFI5HFXNZaEobmM4FKHSGxkQNwBoXufnmCWV2ZIf3uLfwERqL92Sas2lkoOV/mEznI30AeowTnCG1+cUvFRZOrv+5UFUuRSQi83DBFzsXQJjoYEnezA9kVWSVAuamBKRiOZ5YvLngiRJPmIdUC3m4N/6zOK68ouCJy06S/LzrFkWNMS74zwYI1ICiJt7Yt4Khzl35KoP+C1NOLuylj1OyIipActGoOH8z71a4="
matrix:
  include:
    ##
    # Test basic installation with different Travis environments
    ##
    # Ubuntu 12.04 container build
    - os: linux
      sudo: true
      env: COMPONENTS=ifort
before_install:
  - bash -x install-icc.sh --components "${COMPONENTS}"
  - source ~/.bashrc
script:
  # Fortran 90 compiler
  - '[[ "${COMPONENTS}" != *"ifort"* ]] || (ifort -save -o xnfdf.exe save/xnfdf.for && ./xnfdf.exe)'
  - 'diff xnfpdf.dat.test xnfpdf.dat'
  - 'diff xnfpdfmax.dat.test xnfpdfmax.dat.test'

after_script:
  - '[[ ! -z "${INTEL_INSTALL_PATH}" ]] && uninstall_intel_software'

#notifications:
#  email:
#    on_success: change
#    on_failure: change
